service: cfp-api
frameworkVersion: '3'

plugins:
  - serverless-bundle
provider:
  name: aws
  runtime: nodejs14.x

functions:
  cfp:
    handler: handler.cfp
    events:
      - http:
          path: /cfp
          method: POST
          cors: true
